# Generated by Django 5.2.17 on 2026-08-28 14:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField(blank=True, default='')),
                ('audio_key', models.CharField(blank=True, default='', max_length=1024)),
                ('transcript', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('spoken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tz', models.CharField(default='UTC', max_length=64)),
                ('log_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-spoken_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('raw', ''), ('audio_key', ''), _negated=True), name='entry_has_text_or_audio')],
            },
        ),
    ]
