# Generated by Django 5.2.17 on 2026-08-28 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('kind', models.CharField(choices=[('watched', 'watched'), ('free', 'free')], default='free', max_length=8)),
                ('definition', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('model', 'model'), ('user', 'user')], default='model', max_length=8)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='core.entry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='core.tag')),
            ],
            options={
                'ordering': ['tag__slug'],
            },
        ),
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='core.entry')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'version'), name='one_version_per_entry')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='tag_slug_per_user'),
        ),
        migrations.AddConstraint(
            model_name='entrytag',
            constraint=models.UniqueConstraint(fields=('entry', 'tag'), name='one_tag_per_entry'),
        ),
    ]
