# Generated by Django 5.2.17 on 2026-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_entrytag_enrichment_tag_tag_slug_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='transcribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
