# Generated by Django 5.2.17 on 2026-08-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entry_transcribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
