# Generated by Django 5.2.17 on 2026-09-01 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entry_starred'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('model', models.CharField(max_length=100)),
                ('through_entry_id', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('proposed', 'proposed'), ('open', 'open'), ('done', 'done'), ('dismissed', 'dismissed')], default='proposed', max_length=9)),
                ('horizon', models.CharField(choices=[('now', 'now'), ('soon', 'soon'), ('someday', 'someday')], default='soon', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='core.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.todo')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TodoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('seed', 'seed'), ('color', 'color'), ('completion', 'completion')], max_length=10)),
                ('source', models.CharField(choices=[('model', 'model'), ('user', 'user')], default='model', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_entries', to='core.entry')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_entries', to='core.todo')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('todo', 'entry', 'role'), name='one_role_per_todo_entry')],
            },
        ),
    ]
