# Generated by Django 5.2.17 on 2026-09-03 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_synthesisrun_todo_todoitem_todoentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LexiconTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
                ('definition', models.TextField(blank=True, default='')),
                ('boost', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexicon_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['phrase'],
                'constraints': [models.UniqueConstraint(fields=('user', 'phrase'), name='one_phrase_per_user')],
            },
        ),
    ]
